# ===============================
# GitHub Pages Portfolio Config
# Tarekegn Dejen Mengistu
# Hydrology × Machine Learning × Data Science
# ===============================

title: "Tarekegn Dejen Mengistu"
description: "Hydrology · Machine Learning · Uncertainty Modeling · Environmental Data Science"

theme: jekyll-theme-cayman

