theme: jekyll-theme-midnight

title: "Tarekegn Dejen Mengistu"
description: "Hydrology · Machine Learning · Environmental Data Science"

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap




